import Head from 'next/head';
import { useEffect, useState } from 'react';
import { ITick } from '../api';
import { clss } from '../helpers';
import TickerAutocomplete from '../components/TickerAutocomplete';

import Input from '../components/ui/input';


export default function Home() {
  const [selectedTicker, setSelectedTicker] = useState<ITick | null>(null);

  return (
    <div className="container m-auto flex mt-40 justify-center min-h-[100vh]">
      <Head>
        <title>int-shoreline</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="w-[60rem] h-min shadow-lg rounded-md border border-gray-200 p-9 bg-white">
        <div className="my-6 text-sm text text-gray-500">
          {selectedTicker
            ? `${selectedTicker.ticker} ${selectedTicker.name}`
            : 'No Stock Seleted'}
        </div>

          >

          >
        </div>

          <TickerAutocomplete setSelectedTicker={(v) => setSelectedTicker(v)} />
      </div>
    </div>
  );
}
